Move res wrapper
ClinicalGenomicsGBG/general pull request #10
Opened 2022-03-28 14:11 UTC by pbiology

I figured it would be nice to not have to manually keep adding research samples to sFTP folders every time the lab sequences.

This is a wrapper that invokes the move_resaerchsamples script. This should be possible to set up a cronjob, and that way it takes care of this stuff for us.

Since the move_researchdata needs to be root, this script also requires it. Not sure if that was a super nice solution or not

### To test
$ sudo su
$ module load miniconda/4.8.3
$ source activate move_research
(Remove a run from the demuxdir_runlist.txt file)
$ python3 wrapper.py

2022-03-28 14:51 UTC, alvaralmstedt reviewed
README.md path to demultiplexdir could be clarified:
```
move_research) (base) [root@medair1]general:move_res_wrapper$ python3 move_researchdata/move_researchdata.py -d /seqstore/instruments/nextseq_500175_gc/Demultiplexdir/
2022-03-28 16:36:03,337 - INFO - move_researchdata - Looking for data belonging to research projects in /seqstore/instruments/nextseq_500175_gc/Demultiplexdir/.
2022-03-28 16:36:03,338 - ERROR - move_researchdata - Could not SampleSheet.csv @ /seqstore/instruments/nextseq_500175_gc/Demultiplexdir/
(move_research) (base) [root@medair1]general:move_res_wrapper$ python3 move_researchdata/move_researchdata.py -d /seqstore/instruments/nextseq_500175_gc/Demultiplexdir/220325_NB501037_0633_AHLCJ3AFX3
2022-03-28 16:36:27,682 - INFO - move_researchdata - Looking for data belonging to research projects in /seqstore/instruments/nextseq_500175_gc/Demultiplexdir/220325_NB501037_0633_AHLCJ3AFX3.
2022-03-28 16:36:27,683 - INFO - move_researchdata - User has write permissions in /seqstore/remote/outbox/research_projects. Proceeding.
2022-03-28 16:36:27,686 - INFO - move_researchdata - Could not find any research samples in /seqstore/instruments/nextseq_500175_gc/Demultiplexdir/220325_NB501037_0633_AHLCJ3AFX3. Exiting.
(move_research) (base) [root@medair1]general:move_res_wrapper$
```

2022-03-28 14:51 UTC, alvaralmstedt commented on move_researchdata/tools/helpers.py
> +    regex = '^[0-9]{6}_(?:NB|A)[0-9]*_[0-9]{4}_.{10}$' # NovaSeq & NextSeq
This regex will miss methylation arrays. But it probably doesnt matter

2022-03-28 15:04 UTC, pbiology commented on move_researchdata/tools/helpers.py
> +    regex = '^[0-9]{6}_(?:NB|A)[0-9]*_[0-9]{4}_.{10}$' # NovaSeq & NextSeq
Do we have research methylation arrays?

2022-03-28 15:05 UTC, pbiology commented on move_researchdata/configs/wrapper_config.yaml
> +previous_runs_file_path: 'demuxdir_runlist.txt'
I excluded it from the repo cause it keeps adding to it. 
Not sure what would be the best here... But yeah you're right, of course if you run this now you won't have anything in it...

2022-03-28 15:07 UTC, pbiology commented on move_researchdata/configs/wrapper_config.yaml
> +previous_runs_file_path: 'demuxdir_runlist.txt'
Added to the PR description. 
Also can be copied form here.

/home/xlinak/projects/general/move_researchdata/demuxdir_runlist.txt

2022-03-30 05:29 UTC, JPWerling requested changes

2022-03-30 05:29 UTC, JPWerling commented on move_researchdata/wrapper.py
> +              help='Path to wrapper config file')
Could you describe a situation were it's desired to point to another one?

2022-03-30 05:29 UTC, JPWerling commented on move_researchdata/wrapper.py
> +    logger = setup_logger('wrapper', os.path.join(log_path, 'wopr_wrapper.log'))
Is this name intended? Does it reflect the contents of this log?

2022-03-30 05:29 UTC, JPWerling commented on move_researchdata/wrapper.py
> +        previous_runs = [line.rstrip() for line in prev]
Will this not produce the run list file wherever this script is called upon from since there is no full path being handled? One directory change and you are rerunning every run there is

2022-03-30 05:29 UTC, JPWerling commented on move_researchdata/wrapper.py
> +        demux_path = config['instrument_demux_paths'][instrument]
`for instrument, demux_path in config['blabla'].items():`

2022-03-30 05:29 UTC, JPWerling commented on move_researchdata/wrapper.py
> +        subprocess.run(cmd_list)
Why not run the command immediately when first parsing the run instead of appending to list?

2022-03-30 05:29 UTC, JPWerling commented on move_researchdata/wrapper.py
> +            prev.write(os.path.basename(run))
Write the run to the file immediately when processing has begun. Running them all in batch before writing opens up the possibility of another instance of the script processing a run which sits in the current queue, causing all kinds of fun issues.

2022-03-30 05:29 UTC, JPWerling commented on move_researchdata/wrapper.py
> +                runs_to_process.append(run)
Run the command instead?

2022-03-30 06:28 UTC, pbiology commented on move_researchdata/wrapper.py
> +              help='Path to wrapper config file')
I always feel like the config location it self is a bit of a catch-22. I like the idea of things not being hard-coded at all. An example would be if we decide that configs for wrappers should be placed in a central location, if another node wants to re-use our code, or if we want to have an alternate config for another cronjob.

Might be edge-cases, but feels like it adds some flexibility rather than having it completely hard-coded.

2022-03-30 06:31 UTC, pbiology commented on move_researchdata/wrapper.py
> +    logger = setup_logger('wrapper', os.path.join(log_path, 'wopr_wrapper.log'))
Fixed in 34aa626

2022-03-30 06:35 UTC, pbiology commented on move_researchdata/wrapper.py
> +        previous_runs = [line.rstrip() for line in prev]
Ah, I think I see.
Well, if there is no file, it will just raise a FileNotFoundError and crash, so I don't think everything would be re-run.
But I could add a sanity check to make sure there is a runlist file.

2022-03-30 06:35 UTC, pbiology commented on move_researchdata/wrapper.py
> +        demux_path = config['instrument_demux_paths'][instrument]
yeah that's nice. Keep forgetting that one

2022-03-30 06:41 UTC, pbiology commented on move_researchdata/wrapper.py
> +        demux_path = config['instrument_demux_paths'][instrument]
Fixed in 3c26c99

2022-03-30 06:42 UTC, pbiology commented on move_researchdata/wrapper.py
> +        subprocess.run(cmd_list)
I think I had an idea about opening a separate process for each run to process to do it in parallel, but then I scrapped it because it such a small thing. Think this is a remnant. Will re-work.

2022-03-30 10:43 UTC, zobop commented on move_researchdata/wrapper.py
> +        sys.exit()
or perhaps just sys.exit("ERROR: You need to run this wrapper as root!")

2022-03-30 10:44 UTC, JPWerling commented on move_researchdata/wrapper.py
> +              help='Path to wrapper config file')
Fair enough. Not sure how it handles the current default path relative to cwd however.

2022-03-30 10:45 UTC, JPWerling commented on move_researchdata/wrapper.py
> +        previous_runs = [line.rstrip() for line in prev]
My bad, didn't see it was 'r'

2022-03-30 10:46 UTC, JPWerling commented on move_researchdata/wrapper.py
> +        sys.exit()
Or raise custom `UserNotRootError('You need to be root user to run this wrapper')`

2022-03-30 15:22 UTC, pbiology commented on move_researchdata/wrapper.py
> +        subprocess.run(cmd_list)
Fixed

2022-03-31 07:18 UTC, JPWerling requested changes

2022-03-31 07:18 UTC, JPWerling commented on move_researchdata/move_researchdata.py
>                      logger.error(f"Problems copying fastQC files for sample {sample} via rsync.")
Should it continue if one sample fails transfer?

2022-03-31 07:18 UTC, JPWerling commented on move_researchdata/move_researchdata.py
> +            return successful_transfers
This also hides any sample not being successfully moved. If you happen to miss one error being logged in the rapidly moving log output you'd never know one or more samples were missing from just having the number of successful transfers printed unless you knew beforehand how many to expect.

2022-03-31 07:18 UTC, JPWerling commented on move_researchdata/tools/helpers.py
> +    return body
I think it'd be prettier to store it in this fashion. Makes it easier to look at.
```
body = '\n'.join(['While trying to move....',
                           *error_runs,
                           '',
                           f'Please see the following... {log_path},
                           '',
                           'Kind regards...'])
```

2022-03-31 07:18 UTC, JPWerling commented on move_researchdata/wrapper.py
> +sys.path.append("..") # Adds higher directory to python modules path.
I don't understand the comment. Why's this needed?

2022-03-31 07:18 UTC, JPWerling commented on move_researchdata/wrapper.py
> +              help='Path to wrapper config file')
Could add `click.Path()` check here for existence.

2022-03-31 07:18 UTC, JPWerling commented on move_researchdata/wrapper.py
> +              help='Path to wrapper config file')
Will this default value work if wrapper is run from any other directory?

2022-03-31 07:18 UTC, JPWerling commented on move_researchdata/wrapper.py
> +            error_runs = []
This is on the wrong indentation level. Every new run looped through will reset the list as it is now.

2022-03-31 07:18 UTC, JPWerling commented on move_researchdata/wrapper.py
> +                error_runs.append(run)
Might as well slap a `logger.error()` in here

2022-03-31 07:18 UTC, JPWerling commented on move_researchdata/wrapper.py
> +                    prev.write(os.path.basename(run))
If i remember correctly then `.write` does not auto include newlines.

2022-03-31 07:27 UTC, pbiology commented on .gitmodules
> +	url = git@github.com:ClinicalGenomicsGBG/CGG.git
Yeah that could be cool. That feels like something we could add in once we have the CGG repo more set. I think that is an improvement to add for future.

2022-03-31 07:27 UTC, pbiology commented on .gitmodules
> +	url = git@github.com:ClinicalGenomicsGBG/CGG.git
I think that would be cool. I think this is something we could aim to add once we have the CGG repo more set in how to use it. I would suggest to make an issue for this for future but to skip this implementation for now.

2022-03-31 07:28 UTC, pbiology commented on move_researchdata/wrapper.py
> +sys.path.append("..") # Adds higher directory to python modules path.
It came with the copy from stack overflow :)
I'll remove it.

2022-03-31 07:49 UTC, pbiology commented on move_researchdata/move_researchdata.py
> +            return successful_transfers
Added a raise of exception if fastq transfer failed. Just let a warning be logged if fastqc transfer failed as I felt this wasn't as critical.

2022-03-31 07:50 UTC, pbiology commented on move_researchdata/move_researchdata.py
> +            return successful_transfers
Also fixed the indent level

2022-03-31 07:50 UTC, pbiology commented on move_researchdata/move_researchdata.py
>                      logger.error(f"Problems copying fastQC files for sample {sample} via rsync.")
See above. Raise exception if fastq failes, continues if fastqc fails

2022-03-31 07:55 UTC, pbiology commented on move_researchdata/tools/helpers.py
> +    return body
Fixed

2022-03-31 07:56 UTC, pbiology commented on move_researchdata/wrapper.py
> +              help='Path to wrapper config file')
No it does not.. Gonna think about what a better solution is. Ideas?

2022-03-31 07:58 UTC, pbiology commented on move_researchdata/wrapper.py
> +                error_runs.append(run)
I figured the error written in the called function was enough

2022-03-31 08:10 UTC, pbiology commented on move_researchdata/wrapper.py
> +            error_runs = []
Yes, good catch. Fixed

2022-03-31 08:11 UTC, pbiology commented on move_researchdata/wrapper.py
> +                    prev.write(os.path.basename(run))
You are corrected. Added a newline

2022-03-31 08:25 UTC, pbiology commented on move_researchdata/wrapper.py
> +              help='Path to wrapper config file')
Added a solution in 2b5cf7e

2022-03-31 08:27 UTC, JPWerling commented on move_researchdata/wrapper.py
> +                error_runs.append(run)
If an unexpected exception is raised this wont be caught

2022-04-04 09:25 UTC, alvaralmstedt approved these changes
With regard to creating project directories that don't yet exist, functionality could be added to generate the project directory based on the G##-### or whatever project name in the sample-sheet with a newly generated password that is either sent to lab or saved somewhere we can look to give to the users after.

2022-04-04 09:25 UTC, alvaralmstedt commented on move_researchdata/configs/wrapper_config.yaml
> +email:
Does it send an email to lab so they know that the data has been attended to?

2022-04-04 09:25 UTC, alvaralmstedt commented on move_researchdata/tools/helpers.py
> +    regex = '^[0-9]{6}_(?:NB|A)[0-9]*_[0-9]{4}_.{10}$' # NovaSeq & NextSeq
Not at the moment but perhaps in the future

2022-04-04 10:00 UTC, pbiology commented on move_researchdata/configs/wrapper_config.yaml
> +email:
yeah, we can add in whoever we want to get the e-mails. Not sure if labb needs it. Was mainly thinking that we would get the error if something went wrong.

2022-04-04 10:57 UTC, JPWerling approved these changes

2022-04-04 10:57 UTC, JPWerling commented on move_researchdata/wrapper.py
> +                    prev.write(os.path.basename(run) + '\n')
Any risk of another process starting the transfer before the first one has finished and written the run name to the list?

2022-04-04 11:26 UTC, pbiology commented on move_researchdata/wrapper.py
> +                    prev.write(os.path.basename(run) + '\n')
I mean.. I guess. If this process is called every minute or so.
Not sure how to get around that race-condition. Don't want to write to file before move has been completed.
I guess one could have some sort of lock file...

2022-04-04 12:01 UTC, JPWerling commented on move_researchdata/wrapper.py
> +                    prev.write(os.path.basename(run) + '\n')
Moving/copying large fastq's can take quite a while, so even on a 30 minute timer i would be worried about another process starting.

2022-04-04 12:04 UTC, JPWerling commented on move_researchdata/wrapper.py
> +                    prev.write(os.path.basename(run) + '\n')
A process starting on the same run is not only an issue for the fastq copying but also for logging and traceability. Using locks would probably work well for the copying of large files part.

2022-04-04 12:06 UTC, JPWerling commented
> > With regard to creating project directories that don't yet exist, functionality could be added to generate the project directory based on the G##-### or whatever project name in the sample-sheet with a newly generated password that is either sent to lab or saved somewhere we can look to give to the users after.
> 
> Yeah it's for sure kinda annoying that this would crash once a year when there isn't any new folders. The question is, should this be taken care of here, or is that something for another tool, or perhaps that we should migrate away from the chroot jails and have SLIMS as a research portal? Suggestions? @alvaralmstedt @JPWerling

Slims as a research portal is quite a long way away still. Automatically generating users requires input from the lab to provide for contact information. Sending out credentials automatically for access to these files is also problematic (could be circumvented by automatically sending the credentials info to Lab who then sends it onwards).

2022-04-06 07:44 UTC, pbiology commented on move_researchdata/wrapper.py
> +                    prev.write(os.path.basename(run) + '\n')
I agree. Will try to add in a PID lockfile part here with the help of @zobop

2022-04-06 07:45 UTC, pbiology commented
> > > With regard to creating project directories that don't yet exist, functionality could be added to generate the project directory based on the G##-### or whatever project name in the sample-sheet with a newly generated password that is either sent to lab or saved somewhere we can look to give to the users after.
> > 
> > 
> > Yeah it's for sure kinda annoying that this would crash once a year when there isn't any new folders. The question is, should this be taken care of here, or is that something for another tool, or perhaps that we should migrate away from the chroot jails and have SLIMS as a research portal? Suggestions? @alvaralmstedt @JPWerling
> 
> Slims as a research portal is quite a long way away still. Automatically generating users requires input from the lab to provide for contact information. Sending out credentials automatically for access to these files is also problematic (could be circumvented by automatically sending the credentials info to Lab who then sends it onwards).

Agreed. So maybe for now this can be left, and then we deal with the blow each year of generating new folders?

2022-04-13 12:54 UTC, JPWerling approved these changes
Nothing obviously wrong. See comments but not requiring modification

2022-04-13 12:54 UTC, JPWerling commented on move_researchdata/move_researchdata.py
> +    num_transfers = move_data(demultiplexdir, outbox, logger, include_fastqc)
Do we do both this transfer and via slims going forward?

2022-04-13 12:54 UTC, JPWerling commented on move_researchdata/move_researchdata.py
> +def move_data(demultiplexdir, outbox, logger, include_fastqc = False):
`include_fastqc` should be a positional argument for two reasons:
1. You are supplying it as a positional argument in the calling code.
2. There is already a default value associated with it coming from the click interface.

2022-04-13 12:54 UTC, JPWerling commented on move_researchdata/move_researchdata.py
> +                        os.makedirs(fastqc_outbox)
`ok.makedirs(exists_ok=True`

2022-04-13 12:54 UTC, JPWerling commented on move_researchdata/wrapper.py
> +        logger.error(f"{e}")
Does this try-except block need to exist? It's only ever going to log when it attempts to run when already running, which is an expected behaviour.

2022-04-13 13:03 UTC, pbiology commented on move_researchdata/move_researchdata.py
> +    num_transfers = move_data(demultiplexdir, outbox, logger, include_fastqc)
Not 100% sure I understand the comment. My thought is that when lab can select a projects fastq files to move via slims, then this becomes retired.

2022-04-13 13:05 UTC, pbiology commented on move_researchdata/move_researchdata.py
> +def move_data(demultiplexdir, outbox, logger, include_fastqc = False):
I think I follow. The reason it's included here is when the function gets imported directly without the CLI, like in the wrapper

2022-04-13 13:09 UTC, pbiology commented on move_researchdata/wrapper.py
> +        logger.error(f"{e}")
I guess not. Perhaps its too verbose.

2022-04-13 13:23 UTC, merged