Move researchdata
ClinicalGenomicsGBG/general pull request #8
Opened 2022-01-24 14:06 UTC by pbiology

This adds the move_researchdata.py script. The point of this is an automatic way of transferring research data from demultiplex dirs to its respective outbox folder.

Due to the nature of the sftp outbox folder, and they being owned by root, the script also needs to be executed as root:

### To test
```
sudo su
source activate move_research
python3 move_researchdata/move_researchdata.py -d </path/to/demultiplexdir> # Should preferably contain research dat
```

2022-01-24 15:21 UTC, JPWerling requested changes
Logic looks ok but there are improvements to be made.

2022-01-24 15:21 UTC, JPWerling commented on move_researchdata/move_researchdata.py
> +            if not rsync_results:
This check is a bit iffy because the `CompletedProcess` object returned by `subprocess.run()` is always true regardless of the contained returncode.

A better check is using `rsync_results.returncode == 0` or  raise exception on non-zero using `rsync_results.check_returncode()`

2022-01-24 15:21 UTC, JPWerling commented on move_researchdata/move_researchdata.py
> +                fastqc_outbox = os.path.join(project_outbox, run_name, 'fastqc')
This will only succeed if the above comment already creates the folder `run_name`

2022-01-24 15:21 UTC, JPWerling commented on move_researchdata/move_researchdata.py
> +                rsync_cmd.append(fastqc_outbox)
`rsync_cmd = ['rsync', '-P', '--ignore-existing', *fastqc_files, fastqc_outbox]`

2022-01-24 15:21 UTC, JPWerling commented on move_researchdata/move_researchdata.py
> +                if not rsync_results:
Same as above with checking return code

2022-01-24 15:21 UTC, JPWerling commented on move_researchdata/move_researchdata.py
> +                    logger.error(f"Problems copying fastQC files for sample {sample} via rsync. Check the logs.")
Same as above about no logs to look at

2022-01-24 17:09 UTC, pbiology commented on move_researchdata/move_researchdata.py
> +              help='Path to outbox. Default: /seqstore/remote/outbox/research_projects')
It doesn't by deaulf,t by you could add 'show_default'. Fixed in 8aa7cc2

2022-01-24 17:10 UTC, pbiology commented on move_researchdata/move_researchdata.py
> +def setup_logger(name):
This is curious to me. I've always used to "hide" extra functions in the end so you can get to the meat directly when opening the script. I don't really want another file here since it's such a small script so it's nice for it to tbe self contained. 

But if there are standard I'd ofc be happy to adhere to them

2022-01-24 17:19 UTC, pbiology commented on move_researchdata/move_researchdata.py
> +        run_name = os.path.basename(os.path.normpath(demultiplexdir))
Yeah it returned empty with only basename

2022-01-24 17:22 UTC, pbiology commented on move_researchdata/move_researchdata.py
> +        for sample in projects[project]:
I am? Where?

2022-01-24 17:26 UTC, pbiology commented on move_researchdata/move_researchdata.py
> +            fastqc_files = glob.glob(os.path.join(demultiplexdir, 'fastqc/') + sample + "*_fastqc.zip")
Did it like this to try to avoid edge cases. We don't really have any mentions of fastqc files in the "contracts" set up with researchers, but I usually add them out of curtesy since they already get created by demuxer.

The edge case I foresaw was if this runs before all fastqc is completed. Then at least it just doesn't hang.

2022-01-24 17:27 UTC, pbiology commented on move_researchdata/move_researchdata.py
> +            rsync_results = subprocess.run(rsync_cmd)
Given absolute paths, this should be possible to also run from seqstore or medstore.

The one issue I'd rather see is that if this goes to a future webstore on another VLAN, some kind of credentials needs to be used.

2022-01-24 17:30 UTC, pbiology commented on move_researchdata/move_researchdata.py
> +            if sample_project in projects:
Agreed, much nicer. Fixed in d2f6686

2022-01-24 17:30 UTC, pbiology commented on move_researchdata/move_researchdata.py
> +            rsync_cmd.append(fastq_outbox)
Did not know you can do this. Much cleaner for sure. Fixed in d2f6686

2022-01-24 17:31 UTC, pbiology commented on move_researchdata/move_researchdata.py
> +            if not rsync_results:
Yeah, fixed in d2f6686

2022-01-24 17:31 UTC, pbiology commented on move_researchdata/move_researchdata.py
> +                rsync_cmd.append(fastqc_outbox)
Fixed in d2f6686

2022-01-24 17:31 UTC, pbiology commented on move_researchdata/move_researchdata.py
> +                    logger.error(f"Problems copying fastQC files for sample {sample} via rsync. Check the logs.")
Fixed in d2f6686

2022-01-24 17:32 UTC, pbiology commented on move_researchdata/move_researchdata.py
> +                fastqc_outbox = os.path.join(project_outbox, run_name, 'fastqc')
Should be correct now with os.makedirs()
Fixed in d2f6686

2022-01-25 09:58 UTC, JPWerling commented on move_researchdata/move_researchdata.py
> +def setup_logger(name):
I tried to find a good resource about this but it turns out I may have had the wrong idea about function order best practices. There seems to be no PEP8 about it and it comes down to personal preference, so I will retract my previous statement.

2022-01-25 11:08 UTC, JPWerling approved these changes
Looks good. Make changes according to comments if you want but they're not do or die.

2022-01-25 13:57 UTC, merged